spring:
  redis:
    host: 47.113.177.50
    port: 6379
    password: Wch@0817
    database: 0
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
